private = { ignore = true }

accepted = [
    "AGPL-3.0-only",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BlueOak-1.0.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
    "0BSD",
]

targets = [
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
